version: '3.8'

# NOTE - Las versiones de en este primer ejemplo deben ser las mismas que las de los contenedores que se van a utilizar, en este caso mongo:6.0.6 y postgres:15.3

services:

  mongo:
    image: mongo:6.0.6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongo:/data/db

  postgres:
    image: postgres:15.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data

# SECTION - Segundo ejemplo de docker-compose.yml

# version: '3.8'

# services:

#   mongo:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
#       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
#     volumes:
#       - mongo:/data/db

#   postgres:
#     image: postgres:latest
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     volumes:
#       - postgres:/var/lib/postgresql/data

# volumes:
#   mongo:
#   postgres: